//! Golden Business Outcome Harness contract (ADR-0013).
//! Driver and comparator invoke production application/domain services later.
//! Expected oracles are never generated by code under test.

use crate::contracts::MagiProjection;

#[derive(Debug, Clone)]
pub struct GoldenScenario {
    pub scenario_id: String,
    pub scenario_version: String,
    pub business_question: String,
    pub as_of_date: String,
    pub coverage_year: u16,
}

#[derive(Debug, Clone)]
pub struct GoldenOracle {
    pub scenario_id: String,
    pub approval_status: ApprovalStatus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ApprovalStatus {
    PendingOwner,
    Approved,
}

#[derive(Debug, Clone)]
pub struct GoldenCompareReport {
    pub scenario_id: String,
    pub passed: bool,
    pub notes: Vec<String>,
}

/// Production-path driver: same commands and domain services as the application.
pub trait GoldenDriver {
    fn execute(&self, scenario: &GoldenScenario) -> Result<MagiProjection, String>;
}

/// Compares actual production-path results to an independent expected oracle.
pub trait GoldenComparator {
    fn compare(
        &self,
        actual: &MagiProjection,
        expected: &GoldenOracle,
    ) -> GoldenCompareReport;
}
