use golden_harness::repo_root;

#[test]
fn accessibility_primary_actions_have_accessible_names() {
    let app = std::fs::read_to_string(repo_root().join("apps/desktop/src/App.tsx"))
        .expect("App.tsx");
    let ui = std::fs::read_to_string(repo_root().join("packages/ui-components/src/index.tsx"))
        .expect("ui-components");
    let list = std::fs::read_to_string(repo_root().join("packages/ui-components/src/listTable.tsx"))
        .expect("listTable");
    let sources = format!("{app}\n{ui}\n{list}");
    for name in [
        "aria-label=\"finos\"",
        "aria-label=\"Save device name\"",
        "aria-label=\"Create snapshot\"",
        "aria-label=\"Restore published\"",
        "aria-label=\"Acknowledge review\"",
        "aria-label=\"Exit\"",
        "aria-label=\"Import Fidelity or Schwab CSV\"",
        "aria-label=\"Check for updates\"",
        "aria-label=\"Exceptions\"",
        "aria-label=\"Income Plan\"",
        "aria-label=\"Calculator\"",
        "aria-label=\"Position Details\"",
        "aria-label=\"Dashboard\"",
        "aria-label=\"Holdings\"",
        "aria-label=\"New Investment\"",
        "aria-label=\"Add Lot\"",
        "aria-label=\"Import\"",
        "aria-label=\"Settings\"",
        "aria-label=\"Assign lot\"",
        "aria-label=\"Retrieve from market\"",
        "aria-label=\"Mandatory data checklist\"",
        "aria-label=\"Use Most Current as Plan\"",
        "aria-label=\"Save new investment facts\"",
        "aria-label=\"Save stored facts\"",
        "aria-label=\"Cancel position edits\"",
        "aria-label=\"Cancel new investment edits\"",
        "aria-label=\"Cancel add lot edits\"",
        "aria-label=\"Cancel unsaved edits\"",
        "aria-label=\"Open screen with unsaved edits\"",
        "aria-label=\"Save owner period\"",
        "aria-label=\"Calculate window\"",
        "aria-label={`Apply ${tier}`}",
        "aria-label=\"Position dossier\"",
        "aria-label=\"Confirm Plan\"",
        "aria-label=\"Research ROC\"",
        "aria-label=\"Confirm ROC plan\"",
        "aria-label=\"Next wizard step\"",
        "aria-label=\"Previous wizard step\"",
        "aria-label=\"Wizard step guidance\"",
        "aria-label=\"Source research\"",
        "aria-label=\"Issuer site attempts\"",
        "aria-label=\"What we maintain\"",
        "aria-label=\"Maintenance strategy\"",
        "aria-label=\"Standing retrieval template\"",
        "aria-label=\"Source analytics\"",
        "aria-label=\"Future declaration strategy\"",
        "aria-label=\"New investment underlying\"",
        "aria-label=\"Open first lot\"",
        "aria-label=\"Save remaining payment dates\"",
        "aria-label=\"Remaining-year payment dates\"",
        "aria-label=\"Next payment date\"",
        "aria-label={`Remaining pay date ${pay.originalPayOn}`}",
        "aria-label=\"Record bull period\"",
        "aria-label=\"Record bear period\"",
        "aria-label=\"Bull start\"",
        "aria-label=\"Bull end\"",
        "aria-label=\"Bear start\"",
        "aria-label=\"Bear end\"",
        "aria-label=\"Record last price\"",
        "aria-label=\"Refresh last prices\"",
        "aria-label=\"Refresh last price for this symbol\"",
        "aria-label=\"Retrieve declarations for this symbol\"",
        "aria-label=\"Research ROC for this symbol\"",
        "aria-label=\"Position ROC research status\"",
        "aria-label=\"Issuer retrieve\"",
        "aria-label=\"Issuer retrieve status\"",
        "aria-label=\"Issuer retrieve miss summary\"",
        "aria-label=\"Apply issuer sources from provider\"",
        "aria-label=\"Lifetime distributions\"",
        "aria-label=\"Position div type\"",
        "aria-label=\"Needs ROC research\"",
        "aria-label=\"Position is active\"",
        "aria-label=\"Expected tax handling\"",
        "aria-label=\"Declaration weekday\"",
        "aria-label=\"Ex-date weekday\"",
        "aria-label=\"Payday weekday\"",
        "aria-label=\"Price source\"",
        "aria-label=\"Source symbol\"",
        "aria-label=\"Declaration source\"",
        "aria-label=\"Lookback count\"",
        "aria-label=\"Position completeness\"",
        "aria-label=\"Position master\"",
        "aria-label={`Open ${row.symbol} dossier`}",
        "aria-label={`Filter ${label}`}",
        "aria-label={`Clear ${label} filter`}",
        "aria-label=\"Clear filters\"",
        "aria-label=\"Retrieve declarations\"",
        "aria-label=\"Validate import\"",
        "aria-label=\"Approve import\"",
        "aria-label=\"Post import\"",
        "aria-label=\"Previous week\"",
        "aria-label=\"Next week\"",
        "aria-label=\"Filter holdings\"",
        "label=\"Filter calculator\"",
        "label=\"Filter position lots\"",
        "label=\"Filter income plan drilldown\"",
        "label=\"Filter dashboard\"",
        "aria-label={`Sort by ${label}`}",
    ] {
        assert!(sources.contains(name), "missing accessible name {name}");
    }
    assert!(
        !app.contains("Load household seed"),
        "owner UI must not mention household seed"
    );
    assert!(
        !app.contains("ProductionSeedLoad"),
        "owner UI must not call ProductionSeedLoad"
    );
}
